# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'NO=EE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NO=EE

pod 'Alamofire', '~> 4.5'
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift-3.3'
end
